# Generated by Django 3.1.4 on 2021-02-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='result',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='test',
            name='add_info',
        ),
        migrations.AddField(
            model_name='result',
            name='result',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='data.test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='timestamp',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='test',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(default=None, max_length=55),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
