# Generated by Django 3.1.4 on 2021-02-25 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210225_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
